keep_awake:
  target:
    entity:
      integration: stowaway
      domain: switch
  fields:
    minutes:
      example: 60
      selector:
        number:
          min: 1
          max: 43200
          unit_of_measurement: min
    forever:
      default: false
      selector:
        boolean:
release:
  target:
    entity:
      integration: stowaway
      domain: switch
sleep:
  target:
    entity:
      integration: stowaway
      domain: switch
  fields:
    block:
      default: false
      selector:
        boolean:
allow_wake:
  target:
    entity:
      integration: stowaway
      domain: switch
